name: CMake Build on Pull Request

on:
  pull_request:
    branches: [ "none" ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [ Debug ]
    uses: ./.github/workflows/steps.yml
    with:
      build_type: ${{ matrix.build_type }}
