name: Reusable Steps

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        c_compiler: [ gcc ]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Set up GTest
        run: sudo apt-get install libgtest-dev libgmock-dev libbenchmark-dev -y

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
          -DBUILD_DOC=ON
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ inputs.build_type }}

      - name: Test
        if: matrix.os == 'ubuntu-latest' && inputs.build_type == 'Debug'
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ inputs.build_type }} --output-on-failure

      - name: Package build
        if: matrix.os == 'ubuntu-latest' && inputs.build_type == 'Release'
        run: |
          cd ${{ steps.strings.outputs.build-output-dir }}
          cpack --config CPackConfig.cmake

      - name: Upload build artifacts
        if: matrix.os == 'ubuntu-latest' && inputs.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: modern-${{ matrix.os }}
          path: |
            ${{ steps.strings.outputs.build-output-dir }}/packages/*.deb
            ${{ steps.strings.outputs.build-output-dir }}/latex/refman.pdf